### ISSUE TITLE
Invidious - Description is not shown anymore

### ISSUE THREAD

**Issue by LeChatNoir666** [Wint3rmute/baczek.me#25]
Hey Mateusz.

I love your Invidious instance but it looks like the descriptions for videos are broken.
It's not shown anymore...

Sorry to write you here about this but I didn't found an invidious repo in your repo.

Greetings,
Chris

**Comment by Wint3rmute** [comment]
Hey Chris! Thanks for the kind words ;)

I'm not developing invidious myself, just hosting an instance. It seems like the issue you're having has already been reported to the invidious team (https://github.com/iv-org/invidious/issues/3660) and is appearing on multiple instances. 

My server automatically checks for invidious updates, so the instance should be updated right after the descriptions fix lands in the main invidious repo.
